### PR TITLE
Update SMAOffset_Hippocritical_dca.py

### PR DESCRIPTION
**Pull request by cyberjunky**
Return default stake and prevent errors when pair is not in custom variable (after restart for example)

### CODE REVIEW

**Comment by hippocritical** [comment]
hi, just saw that you made a commit, will look at it at the weekend :)

thanks for doing a PR!

**Comment by cyberjunky** [comment]
> hi, just saw that you made a commit, will look at it at the weekend :)
> 
> thanks for doing a PR!

Yes correct some minor fixes, there is still an issue when you have unlimited stake amount and running our of funds, but that can also be caused by the overbought param, did check yet.

**Comment by hippocritical** [comment]
Hey, why should this be necessary? A pair currently is calculated upon entering the first time that means it has a valid signal including the stake amount already.

Could you explain why this error would occur?

**Comment by cyberjunky** [comment]
I believe the issue was a KeyError on a restart of freqtrade with one or more open trades. (since custom_info is empty then)

**Review by hippocritical — APPROVED** [review]

**Pull request merged**
